### ISSUE TITLE
Generator crashes for "SmICS-Befund"

### ISSUE THREAD

**Issue by LtSurgekopf** [ehrbase/openEHR_SDK#109]
Hi, I am trying to generate classes for the HiGHmed UC IC templates, and was unable to do so for the "SmICS-Befund" template with the following bug occuring on the latest develop:

## Steps to reproduce ## 

Generate the template class from the attached OPT file 
[SmICS-Befund.opt.gz](https://github.com/ehrbase/openEHR_SDK/files/5391824/SmICS-Befund.opt.gz)
using `java -jar generator-0.3.7.jar  -opt /tmp/SmICS-Befund.opt -out /tmp -package foo.bar`

## Actual result ##

The following exception is thrown:

`
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at org.ehrbase.client.classgenerator.ClassGenerator.sanitizeNumber(ClassGenerator.java:335)
	at org.ehrbase.client.classgenerator.ClassGenerator.buildFieldName(ClassGenerator.java:438)
	at org.ehrbase.client.classgenerator.ClassGenerator.addField(ClassGenerator.java:402)
	at org.ehrbase.client.classgenerator.ClassGenerator.addSimpleField(ClassGenerator.java:294)
	at org.ehrbase.client.classgenerator.ClassGenerator.addChoiceField(ClassGenerator.java:251)
	at org.ehrbase.client.classgenerator.ClassGenerator.build(ClassGenerator.java:214)
	at org.ehrbase.client.classgenerator.ClassGenerator.addComplexField(ClassGenerator.java:307)
	at org.ehrbase.client.classgenerator.ClassGenerator.build(ClassGenerator.java:212)
	at org.ehrbase.client.classgenerator.ClassGenerator.addComplexField(ClassGenerator.java:307)
	at org.ehrbase.client.classgenerator.ClassGenerator.build(ClassGenerator.java:212)
	at org.ehrbase.client.classgenerator.ClassGenerator.addComplexField(ClassGenerator.java:307)
	at org.ehrbase.client.classgenerator.ClassGenerator.build(ClassGenerator.java:212)
	at org.ehrbase.client.classgenerator.ClassGenerator.generate(ClassGenerator.java:170)
	at org.ehrbase.client.classgenerator.ClassGenerator.main(ClassGenerator.java:141)
`
The offending field is the `[openEHR-EHR-COMPOSITION.report.v1]/context/other_context[at0001]/items[openEHR-EHR-CLUSTER.eventsummary.v0]/items[at0007]/items[at0010]` ("ID der Person"), a choice field for IDs or URIs. The method `sanitizeNumber` is called with the empty string `""`, because the method `buildFieldName` is called with the name `///` (just the term divider).

Obviously, returning the empty string won't work, because that isn't a valid field name in Java. I don't understand how the path `///` is assembled, so my instinct tells me that the error is located there. Adding a default value in `sanitizeNumber` (or `buildFieldName`) might also be a good idea.

## Expected result ##

The name of the field should be correctly created and no exception should be thrown.

## Success criteria ##

- [x] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by LtSurgekopf** [comment]
Adding a default value (`hello`) in buildFieldName and returning the unmodified value in `sanitizeNumber` made the exception disappear (unsurprisingly). Because of my lack of experience with openEHR, I'm not sure at all what the implications of such a "fix" would be though: 

ContextEventSummaryChoice.java
```java
package foo.bar.smicsbefundcomposition.definition;

public interface ContextEventsummaryChoice {
}
```

ContextEventsummaryDvidentifier.java **(shouldn't the `@Path` have a value?!)**
```java
package foo.bar.smicsbefundcomposition.definition;

import com.nedap.archie.rm.datavalues.DvIdentifier;
import org.ehrbase.client.annotations.Entity;
import org.ehrbase.client.annotations.OptionFor;
import org.ehrbase.client.annotations.Path;

@Entity
@OptionFor("DV_IDENTIFIER")
public class ContextEventsummaryDvidentifier implements ContextEventsummaryChoice {
  @Path("")
  private DvIdentifier hello;

  public void setHello(DvIdentifier hello) {
     this.hello = hello;
  }

  public DvIdentifier getHello() {
     return this.hello ;
  }
}
```

**Comment by stefanspiska** [comment]
@LtSurgekopf  This should be fixed in https://github.com/ehrbase/openEHR_SDK/pull/110
The empty path is correct.

**Comment by LtSurgekopf** [comment]
Yep, I can confirm that #110 fixes this. Feel free to close this issue after merging!
