### ISSUE TITLE
Generator fails to generate classes from opt: invalid enum 38_C

### ISSUE THREAD

**Issue by SevKohler** [ehrbase/openEHR_SDK#113]
## Steps to reproduce ## 

1. Download opt from this [template](https://ckm.highmed.org/ckm/templates/1246.169.743).
2. java -jar generator-0.3.7.jar -opt ../../../fhir-bridge/src/main/resources/opt/D4L_questionnaire.opt -out ../../../fhir-bridge/src/main/java -package org.ehrbase.fhirbridge.opt

## Actual result ##
```java
[main] INFO org.ehrbase.client.terminology.TerminologyProvider - Unknown  value hr in Terminology ISO_639-1
[main] INFO org.ehrbase.client.terminology.TerminologyProvider - Unknown  value de-lu in Terminology ISO_639-1
[main] INFO org.ehrbase.client.terminology.TerminologyProvider - Unknown  value pt in Terminology ISO_639-1
Exception in thread "main" java.lang.IllegalArgumentException: not a valid enum constant: 38_C
	at com.squareup.javapoet.Util.checkArgument(Util.java:53)
	at com.squareup.javapoet.TypeSpec$Builder.addEnumConstant(TypeSpec.java:514)
	at org.ehrbase.client.classgenerator.ClassGenerator.lambda$buildEnumValueSet$3(ClassGenerator.java:362)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.ehrbase.client.classgenerator.ClassGenerator.buildEnumValueSet(ClassGenerator.java:360)
	at org.ehrbase.client.classgenerator.ClassGenerator.lambda$addField$4(ClassGenerator.java:386)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at org.ehrbase.client.classgenerator.ClassGenerator.addField(ClassGenerator.java:386)
	at org.ehrbase.client.classgenerator.ClassGenerator.lambda$addSimpleField$2(ClassGenerator.java:298)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.ehrbase.client.classgenerator.ClassGenerator.addSimpleField(ClassGenerator.java:298)
	at org.ehrbase.client.classgenerator.ClassGenerator.build(ClassGenerator.java:210)
	at org.ehrbase.client.classgenerator.ClassGenerator.addComplexField(ClassGenerator.java:307)
	at org.ehrbase.client.classgenerator.ClassGenerator.build(ClassGenerator.java:212)
	at org.ehrbase.client.classgenerator.ClassGenerator.addComplexField(ClassGenerator.java:307)
	at org.ehrbase.client.classgenerator.ClassGenerator.build(ClassGenerator.java:212)
	at org.ehrbase.client.classgenerator.ClassGenerator.addComplexField(ClassGenerator.java:307)
	at org.ehrbase.client.classgenerator.ClassGenerator.build(ClassGenerator.java:212)
	at org.ehrbase.client.classgenerator.ClassGenerator.generate(ClassGenerator.java:170)
	at org.ehrbase.client.classgenerator.ClassGenerator.main(ClassGenerator.java:141)
```
## Expected result ##

success of generator

## Success criteria ##

- [ ] The defect has been fixed
- [ ] The defect is checked by an unit or an integration test (Robot)
- [ ] Merge Request approved
- [ ] Unit tests passed
- [ ] Build without errors
- [ ] Release notes prepared
- [ ] Runtime warnings

**Comment by SevKohler** [comment]
@stefanspiska any idea?

**Comment by stefanspiska** [comment]
@SevKohler I will try to take a look on Monday

**Comment by stefanspiska** [comment]
should be fixed in https://github.com/ehrbase/openEHR_SDK/pull/116
