### ISSUE TITLE
Allow to use custom class loaders in composition endpoint

### ISSUE THREAD

**Issue by Ivan1pl** [ehrbase/openEHR_SDK#377]
## Background ##

We are dynamically loading generated classes at runtime using a custom class loader in our client application. Because of this, class graph scan cannot find them.
```
java.lang.IndexOutOfBoundsException: Index: 0
        at java.base/java.util.Collections$EmptyList.get(Collections.java:4483)
        at org.ehrbase.client.flattener.Flattener.flatten(Flattener.java:79)
        at org.ehrbase.client.openehrclient.defaultrestclient.DefaultRestCompositionEndpoint.mergeCompositionEntity(DefaultRestCompositionEndpoint.java:75)
```
We would like to use our custom class loader in composition endpoint, but currently it is not possible. Some classes used within methods we would need to override use package-private access, preventing us from overriding the method.

## Acceptance criteria ##

Some very simple changes would be enough, here is my proposition for how it could be done:

`Flattener.java` (current):
```java
    public <T> T flatten(RMObject locatable, Class<T> clazz) {
        try {
            //...
            // lines 70-74:
            classGraph = new ClassGraph()
                    .enableClassInfo()
                    .enableAnnotationInfo()
                    .acceptPackages(packageNames)
                    .scan();
            //...
        } finally {
            if (classGraph != null) {
                classGraph.close();
            }
        }
    }
```

`Flattener.java` (proposition):
```java
    public <T> T flatten(RMObject locatable, Class<T> clazz) {
        try {
            //...
            classGraph = createClassGraph(packageNames).scan();
            //...
        } finally {
            if (classGraph != null) {
                classGraph.close();
            }
        }
    }

    protected ClassGraph createClassGraph(String packageNames) {
        return new ClassGraph()
                .enableClassInfo()
                .enableAnnotationInfo()
                .acceptPackages(packageNames);
    }
```

We could then provide our custom flattener and override this method like this:
```java
    @Override
    protected ClassGraph createClassGraph(String packageNames) {
        return super.createClassGraph(packageNames).overrideClassLoaders(ourClassLoader);
    }
```

Similar change would be needed in `DefaultRestCompositionEndpoint`, so that we can override it and provide our custom flattener.

`DefaultRestCompositionEndpoint.java` (current):
```java
    @Override
    public <T> T mergeCompositionEntity(T entity) {
        //...
        // line 75:
        entity = (T) new Flattener(defaultRestClient.getTemplateProvider()).flatten(composition, entity.getClass());
        //...
    }

    //...

    // lines 111-116
    @Override
    public <T> Optional<T> find(UUID compositionId, Class<T> clazz) {
        Optional<Composition> composition = findRaw(compositionId);

        return composition.map(c -> new Flattener(defaultRestClient.getTemplateProvider()).flatten(c, clazz));
    }
```

`DefaultRestCompositionEndpoint.java` (proposition):
```java
    @Override
    public <T> T mergeCompositionEntity(T entity) {
        //...
        entity = (T) createFlattener(defaultRestClient.getTemplateProvider()).flatten(composition, entity.getClass());
        //...
    }

    //...

    @Override
    public <T> Optional<T> find(UUID compositionId, Class<T> clazz) {
        Optional<Composition> composition = findRaw(compositionId);

        return composition.map(c -> createFlattener(defaultRestClient.getTemplateProvider()).flatten(c, clazz));
    }

    protected Flattener createFlattener(TemplateProvider templateProvider) {
        return new Flattener(templateProvider);
    }
```

We could then provide our own composition endpoint and override this method like this:
```java
    @Override
    protected Flattener createFlattener(TemplateProvider templateProvider) {
        return new CustomFlattener(templateProvider, ourClassLoader);
    }
```

As an alternative solution, maybe custom class loaders could be passed in a constructor of `DefaultRestCompositionEndpoint`.

- [ ] A way to provide custom class loaders for flattener within `DefaultRestCompositionEndpoint`.

## Definition of Done ##

- [ ] Review / Merge request approved (P2P session)
- [ ] Unit tests passed
- [ ] Acceptance criteria fulfilled
- [ ] Build without errors

**Comment by stefanspiska** [comment]
@Ivan1pl 
Your changes look reasonable. If you could provide them as a PR , I would take a look and merge it.
