### ISSUE TITLE
Method not found: setMagnitude

### ISSUE THREAD

**Issue by SevKohler** [ehrbase/openEHR_SDK#426]
# Environment information
openjdk 19.0.2 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7)
OpenJDK 64-Bit Server VM (build 19.0.2+7, mixed mode)

Maven home: /opt/maven
Java version: 19.0.2, vendor: N/A, runtime: /usr/lib/jvm/java-19-openjdk
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "6.1.12-1-manjaro", arch: "amd64", family: "unix"

openEHR_SDK 1.24.0
# Steps to reproduce
mvn clean install
# Actual result

```
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ client ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.ehrbase.client.classgenerator.OldDtoModelTest
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 1.822 s <<< FAILURE! - in org.ehrbase.client.classgenerator.OldDtoModelTest
[ERROR] org.ehrbase.client.classgenerator.OldDtoModelTest.testUnflattenCorona  Time elapsed: 1.126 s  <<< ERROR!
org.ehrbase.client.exception.ClientException: Method not found: setMagnitude
	at org.ehrbase.client.classgenerator.OldDtoModelTest.testUnflattenCorona(OldDtoModelTest.java:142)
Caused by: java.beans.IntrospectionException: Method not found: setMagnitude
	at org.ehrbase.client.classgenerator.OldDtoModelTest.testUnflattenCorona(OldDtoModelTest.java:142)

[ERROR] org.ehrbase.client.classgenerator.OldDtoModelTest.testRoundTrip  Time elapsed: 0.532 s  <<< ERROR!
org.ehrbase.client.exception.ClientException: Method not found: setMagnitude
	at org.ehrbase.client.classgenerator.OldDtoModelTest.checkTestCase(OldDtoModelTest.java:163)
	at org.ehrbase.client.classgenerator.OldDtoModelTest.testRoundTrip(OldDtoModelTest.java:113)
Caused by: java.beans.IntrospectionException: Method not found: setMagnitude
	at org.ehrbase.client.classgenerator.OldDtoModelTest.checkTestCase(OldDtoModelTest.java:163)
	at org.ehrbase.client.classgenerator.OldDtoModelTest.testRoundTrip(OldDtoModelTest.java:113)

[ERROR] org.ehrbase.client.classgenerator.OldDtoModelTest.testFlattenCorona  Time elapsed: 0.156 s  <<< ERROR!
org.ehrbase.client.exception.ClientException: Method not found: setMagnitude
	at org.ehrbase.client.classgenerator.OldDtoModelTest.testFlattenCorona(OldDtoModelTest.java:126)
Caused by: java.beans.IntrospectionException: Method not found: setMagnitude
	at org.ehrbase.client.classgenerator.OldDtoModelTest.testFlattenCorona(OldDtoModelTest.java:126)

[INFO] Running org.ehrbase.client.flattener.FlattenerTest
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.sample_blood_pressure.v1]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.sample_blood_pressure.v1]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.sample_blood_pressure.v1]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoFromCompositionWalker - No Field in dto BloodPressureTrainingSampleObservation for path WebTemplateNode{id='offset', name='offset', rmType='DV_DURATION', aqlPath='/content[openEHR-EHR-OBSERVATION.sample_blood_pressure.v1]/data[at0001]/events[at0002]/offset'}
[main] WARN org.ehrbase.client.flattener.DtoFromCompositionWalker - No Field in dto BloodpressureListDe for path WebTemplateNode{id='category', name='category', rmType='DV_CODED_TEXT', aqlPath='/category'}
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_temperature.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_temperature.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_temperature.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_temperature.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_temperature.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_temperature.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-ADMIN_ENTRY.episodeofcare.v0]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-ADMIN_ENTRY.episodeofcare.v0]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-ADMIN_ENTRY.episodeofcare.v0]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_weight.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_weight.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_weight.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoFromCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.height.v2]/data[at0001]/events[at0002] is choice but missing OptionFor: Transforming INTERVAL_EVENT to POINT_EVENT 
[ERROR] Tests run: 9, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 0.807 s <<< FAILURE! - in org.ehrbase.client.flattener.FlattenerTest
[ERROR] org.ehrbase.client.flattener.FlattenerTest.testFlattenEhrbaseBloodPressureSimpleDeV0  Time elapsed: 0.127 s  <<< ERROR!
org.ehrbase.client.exception.ClientException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.FlattenerTest.testFlattenEhrbaseBloodPressureSimpleDeV0(FlattenerTest.java:216)
Caused by: java.beans.IntrospectionException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.FlattenerTest.testFlattenEhrbaseBloodPressureSimpleDeV0(FlattenerTest.java:216)

[ERROR] org.ehrbase.client.flattener.FlattenerTest.testFlatten  Time elapsed: 0.081 s  <<< ERROR!
org.ehrbase.client.exception.ClientException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.FlattenerTest.testFlatten(FlattenerTest.java:77)
Caused by: java.beans.IntrospectionException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.FlattenerTest.testFlatten(FlattenerTest.java:77)

[ERROR] org.ehrbase.client.flattener.FlattenerTest.testFlattenEhrbaseMultiOccurrenceDeV1  Time elapsed: 0.072 s  <<< ERROR!
org.ehrbase.client.exception.ClientException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.FlattenerTest.testFlattenEhrbaseMultiOccurrenceDeV1(FlattenerTest.java:254)
Caused by: java.beans.IntrospectionException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.FlattenerTest.testFlattenEhrbaseMultiOccurrenceDeV1(FlattenerTest.java:254)

[ERROR] org.ehrbase.client.flattener.FlattenerTest.testFlattenCorona  Time elapsed: 0.139 s  <<< ERROR!
org.ehrbase.client.exception.ClientException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.FlattenerTest.testFlattenCorona(FlattenerTest.java:286)
Caused by: java.beans.IntrospectionException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.FlattenerTest.testFlattenCorona(FlattenerTest.java:286)

[ERROR] org.ehrbase.client.flattener.FlattenerTest.testFlattenAltEvents  Time elapsed: 0.056 s  <<< ERROR!
org.ehrbase.client.exception.ClientException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.FlattenerTest.testFlattenAltEvents(FlattenerTest.java:299)
Caused by: java.beans.IntrospectionException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.FlattenerTest.testFlattenAltEvents(FlattenerTest.java:299)

[ERROR] org.ehrbase.client.flattener.FlattenerTest.testFlattenSingleEventIntervallEvent  Time elapsed: 0.066 s  <<< ERROR!
org.ehrbase.client.exception.ClientException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.FlattenerTest.testFlattenSingleEventIntervallEvent(FlattenerTest.java:203)
Caused by: java.beans.IntrospectionException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.FlattenerTest.testFlattenSingleEventIntervallEvent(FlattenerTest.java:203)

[ERROR] org.ehrbase.client.flattener.FlattenerTest.testFlattenSingleEventPointEvent  Time elapsed: 0.055 s  <<< ERROR!
org.ehrbase.client.exception.ClientException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.FlattenerTest.testFlattenSingleEventPointEvent(FlattenerTest.java:174)
Caused by: java.beans.IntrospectionException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.FlattenerTest.testFlattenSingleEventPointEvent(FlattenerTest.java:174)

[INFO] Running org.ehrbase.client.flattener.UnflattenerTest
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.sample_blood_pressure.v1]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.sample_blood_pressure.v1]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.sample_blood_pressure.v1]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_weight.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_weight.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_weight.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-ADMIN_ENTRY.episodeofcare.v0]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-ADMIN_ENTRY.episodeofcare.v0]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-ADMIN_ENTRY.episodeofcare.v0]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_temperature.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_temperature.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_temperature.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_temperature.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_temperature.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /content[openEHR-EHR-OBSERVATION.body_temperature.v2]/subject is choice but PartySelf is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[main] WARN org.ehrbase.client.flattener.DtoToCompositionWalker - Path /composer is choice but PartyIdentified is missing OptionFor
[ERROR] Tests run: 9, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.295 s <<< FAILURE! - in org.ehrbase.client.flattener.UnflattenerTest
[ERROR] org.ehrbase.client.flattener.UnflattenerTest.testUnflattenCorona  Time elapsed: 0.104 s  <<< ERROR!
org.ehrbase.client.exception.ClientException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.UnflattenerTest.testUnflattenCorona(UnflattenerTest.java:201)
Caused by: java.beans.IntrospectionException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.UnflattenerTest.testUnflattenCorona(UnflattenerTest.java:201)

[ERROR] org.ehrbase.client.flattener.UnflattenerTest.testUnflattenInterval  Time elapsed: 0.106 s  <<< ERROR!
org.ehrbase.client.exception.ClientException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.UnflattenerTest.testUnflattenInterval(UnflattenerTest.java:112)
Caused by: java.beans.IntrospectionException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.UnflattenerTest.testUnflattenInterval(UnflattenerTest.java:112)

[INFO] Running org.ehrbase.client.flattener.RoundTripTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.165 s <<< FAILURE! - in org.ehrbase.client.flattener.RoundTripTest
[ERROR] org.ehrbase.client.flattener.RoundTripTest.testRoundTrip  Time elapsed: 0.164 s  <<< ERROR!
org.ehrbase.client.exception.ClientException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.RoundTripTest.checkTestCase(RoundTripTest.java:171)
	at org.ehrbase.client.flattener.RoundTripTest.testRoundTrip(RoundTripTest.java:156)
Caused by: java.beans.IntrospectionException: Method not found: setMagnitude
	at org.ehrbase.client.flattener.RoundTripTest.checkTestCase(RoundTripTest.java:171)
	at org.ehrbase.client.flattener.RoundTripTest.testRoundTrip(RoundTripTest.java:156)

[INFO] Running org.ehrbase.client.building.OptSkeletonBuilderTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.08 s - in org.ehrbase.client.building.OptSkeletonBuilderTest
[INFO] Running org.ehrbase.client.normalizer.NormalizerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.04 s - in org.ehrbase.client.normalizer.NormalizerTest
[INFO] Running org.ehrbase.client.openehrclient.defaultrestclient.systematic.comparator.datetime.CompareCanonicalDvDateTimeTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 s - in org.ehrbase.client.openehrclient.defaultrestclient.systematic.comparator.datetime.CompareCanonicalDvDateTimeTest
[INFO] Running org.ehrbase.client.openehrclient.defaultrestclient.systematic.CanonicalUtilTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in org.ehrbase.client.openehrclient.defaultrestclient.systematic.CanonicalUtilTest
[INFO] Running org.ehrbase.client.aql.containment.ContainmentNUMResearchTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.ehrbase.client.aql.containment.ContainmentNUMResearchTest
[INFO] Running org.ehrbase.client.aql.containment.ContainmentExpressionTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.ehrbase.client.aql.containment.ContainmentExpressionTest
[INFO] Running org.ehrbase.client.aql.containment.ContainmentTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.195 s - in org.ehrbase.client.aql.containment.ContainmentTest
[INFO] Running org.ehrbase.client.aql.query.EntityQueryTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in org.ehrbase.client.aql.query.EntityQueryTest
[INFO] Running org.ehrbase.client.aql.condition.ConditionTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in org.ehrbase.client.aql.condition.ConditionTest
[INFO] Running org.ehrbase.client.aql.parameter.AqlValueTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.ehrbase.client.aql.parameter.AqlValueTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   OldDtoModelTest.testFlattenCorona:126 » Client Method not found: setMagnitude
[ERROR]   OldDtoModelTest.testRoundTrip:113->checkTestCase:163 » Client Method not found...
[ERROR]   OldDtoModelTest.testUnflattenCorona:142 » Client Method not found: setMagnitud...
[ERROR]   FlattenerTest.testFlatten:77 » Client Method not found: setMagnitude
[ERROR]   FlattenerTest.testFlattenAltEvents:299 » Client Method not found: setMagnitude
[ERROR]   FlattenerTest.testFlattenCorona:286 » Client Method not found: setMagnitude
[ERROR]   FlattenerTest.testFlattenEhrbaseBloodPressureSimpleDeV0:216 » Client Method no...
[ERROR]   FlattenerTest.testFlattenEhrbaseMultiOccurrenceDeV1:254 » Client Method not fo...
[ERROR]   FlattenerTest.testFlattenSingleEventIntervallEvent:203 » Client Method not fou...
[ERROR]   FlattenerTest.testFlattenSingleEventPointEvent:174 » Client Method not found: ...
[ERROR]   RoundTripTest.testRoundTrip:156->checkTestCase:171 » Client Method not found: ...
[ERROR]   UnflattenerTest.testUnflattenCorona:201 » Client Method not found: setMagnitud...
[ERROR]   UnflattenerTest.testUnflattenInterval:112 » Client Method not found: setMagnit...
[INFO] 
[ERROR] Tests run: 46, Failures: 0, Errors: 13, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for root 1.25.0-SNAPSHOT:
[INFO] 
[INFO] openEHR SDK ........................................ SUCCESS [  1.855 s]
[INFO] root ............................................... SUCCESS [ 11.678 s]
[INFO] opt-1.4 ............................................ SUCCESS [ 12.283 s]
[INFO] util ............................................... SUCCESS [  3.822 s]
[INFO] aql ................................................ SUCCESS [ 15.772 s]
[INFO] terminology ........................................ SUCCESS [  0.904 s]
[INFO] test-data .......................................... SUCCESS [  0.276 s]
[INFO] web-template ....................................... SUCCESS [  5.275 s]
[INFO] building ........................................... SUCCESS [  3.131 s]
[INFO] serialisation ...................................... SUCCESS [ 12.283 s]
[INFO] response-dto ....................................... SUCCESS [  1.017 s]
[INFO] validation ......................................... SUCCESS [ 13.178 s]
[INFO] client ............................................. FAILURE [  6.143 s]
[INFO] generator .......................................... SKIPPED
[INFO] generator-maven-plugin ............................. SKIPPED
[INFO] serialisation_conformance_test ..................... SKIPPED
[INFO] example-generator .................................. SKIPPED
[INFO] test-coverage ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:43 min
[INFO] Finished at: 2023-03-13T16:19:06+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project client: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/severink/repos/openEHR_SDK/client/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :client
```

entire thing https://pastebin.com/RqdacgKd

# Expected result

should build 

# Further information
Clean system, first maven package i installed
> Add additional information, if needed.

**Comment by SevKohler** [comment]
Maybe Maven version is too new ?

**Comment by stefanspiska** [comment]
@SevKohler 

woks on my local system as well as the ci.

**Comment by SevKohler** [comment]
@stefanspiska  yeah i know, saw the CI, i just dont know what to do else, i literally reinstalled the OS. 
Which JDK and what maven version do you have

**Comment by stefanspiska** [comment]
@SevKohler 

check if you ide dos auto-format. I had issues with wrongly formatted opts.  

also set the test to ignore and check if the other test are running.

**Comment by stefanspiska** [comment]
@SevKohler 
maven 3.8.1
java: temurin:11

**Comment by SevKohler** [comment]
@stefanspiska 
Switched to other laptop, with Java 17 worked. 
If i changed to jdk 19 i got the same bug.
