### ISSUE TITLE
Generator error: IllegalArgumentException: not a valid name: 24HourAverageDefiningcode

### ISSUE THREAD

**Issue by ppazos** [ehrbase/openEHR_SDK#58]
Tried to generate code for this OPT:

[Template A.opt.txt](https://github.com/ehrbase/openEHR_SDK/files/4956645/Template.A.opt.txt)

And got:

```
Exception in thread "main" java.lang.IllegalArgumentException: not a valid name: 24HourAverageDefiningcode
	at com.squareup.javapoet.Util.checkArgument(Util.java:53)
	at com.squareup.javapoet.TypeSpec$Builder.<init>(TypeSpec.java:413)
	at com.squareup.javapoet.TypeSpec$Builder.<init>(TypeSpec.java:392)
	at com.squareup.javapoet.TypeSpec.enumBuilder(TypeSpec.java:128)
	at org.ehrbase.client.classgenerator.ClassGenerator.buildEnumValueSet(ClassGenerator.java:319)
	at org.ehrbase.client.classgenerator.ClassGenerator.addField(ClassGenerator.java:359)
	at org.ehrbase.client.classgenerator.ClassGenerator.lambda$addSimpleField$3(ClassGenerator.java:280)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.ehrbase.client.classgenerator.ClassGenerator.addSimpleField(ClassGenerator.java:280)
	at org.ehrbase.client.classgenerator.ClassGenerator.build(ClassGenerator.java:194)
	at org.ehrbase.client.classgenerator.ClassGenerator.addComplexField(ClassGenerator.java:289)
	at org.ehrbase.client.classgenerator.ClassGenerator.build(ClassGenerator.java:196)
	at org.ehrbase.client.classgenerator.ClassGenerator.addComplexField(ClassGenerator.java:289)
	at org.ehrbase.client.classgenerator.ClassGenerator.build(ClassGenerator.java:196)
	at org.ehrbase.client.classgenerator.ClassGenerator.generate(ClassGenerator.java:154)
	at org.ehrbase.client.classgenerator.ClassGenerator.main(ClassGenerator.java:113)

```

**Comment by stefanspiska** [comment]
@ppazos that should be fixed on dev

**Comment by ppazos** [comment]
@stefanspiska tested and the error is fixed.
